from typing import Any, Optional, Union
from scipy.sparse import csr_array
from networkx.classes.graph import Graph
# default values
DEFAULT_RECURSION_LIMIT = 1024**2
DEFAULT_ENTROPY_STEPS = 1000
DEFAULT_ENTROPY_LEXPONENT = -3
DEFAULT_ENTROPY_HEXPONENT = 6

DIR_SRC_DEFAULT = "src/"
DIR_PCK_DEFAULT = "LRGSG_package/"
DIR_PLT_DEFAULT = "plot/"
DIR_DAT_DEFAULT = "data/"

DIR_GRAPH_DEFAULT = "graphs/"
DEFAULT_ISING_OUTDIR = "ising/"
DEFAULT_VOTER_OUTDIR = "voter/"
DEFAULT_LRGSG_OUTDIR = "lrgsg/"
DEFAULT_PHTRA_OUTDIR = "phtra/"
DEFAULT_ERGRAPH_SGPATH = "er/"
DEFAULT_LATTICE2D_PATHABBRV = 'l2d_'
DEFAULT_LATTICE2D_GEOMETRY = 'squared'

DEFAULT_LATTICE2D_SIDE1 = 32
DEFAULT_LATTICE2D_SIDE2 = 0 # there is a precise reason for this to be 0!

DEFAULT_DATA_LATTICE2DSQ_OUTDIR = DIR_DAT_DEFAULT + DEFAULT_LATTICE2D_PATHABBRV + DEFAULT_LATTICE2D_GEOMETRY
DEFAULT_ISING_NOCLUST = 5
DEFAULT_MAX_DIGITS_ROUND_SIGFIG = 18
DEFAULT_NUNMBER_AVERAGES = 100
DEFAULT_SPIKE_THRESHOLD = 0.05
DEFAULT_MAX_THRESHOLD = 2 * DEFAULT_SPIKE_THRESHOLD
DEFAULT_MIN_PFLIPVAL = 0.0
DEFAULT_MAX_PFLIPVAL = 1.0
# default lists
DEFLIST_LATTICE2D_GEOMETRIES = ['triangular', DEFAULT_LATTICE2D_GEOMETRY, 'hexagonal']
DEFLIST_LATTICE2D_GEOABBRV = ['trLattice', 'sqLattice', 'hxLattice']
DEFAULT_ERGRAPH_ABBRV = "randGraph"
# extensions
ePDF = ".pdf"
eTXT = ".txt"
eBIN = ".bin"
eMP4 = ".mp4"
# paths
PATH_ROOTF = "LRG-Signed"