# default values
DEFAULT_ENTROPY_STEPS = 1000
DEFAULT_ENTROPY_LEXPONENT = -3
DEFAULT_ENTROPY_HEXPONENT = 6
DEFAULT_DATA_OUTDIR = "data/"
DEFAULT_PLOT_OUTDIR = "plot/"
DEFAULT_GRAPH_OUTDIR = "graphs/"
DEFAULT_ISING_OUTDIR = "ising/"
DEFAULT_VOTER_OUTDIR = "voter/"
DEFAULT_DATA_LATTICE2DSQ_OUTDIR = DEFAULT_DATA_OUTDIR + "l2d_squared/"
DEFAULT_LATTICE2D_PATHABBRV = 'l2d'
DEFAULT_LATTICE2D_GEOMETRY = 'squared'
DEFAULT_ISING_NOCLUST = 5
DEFAULT_MAX_DIGITS_ROUND_SIGFIG = 18
DEFAULT_NUNMBER_AVERAGES = 100
DEFAULT_SPIKE_THRESHOLD = 0.05
DEFAULT_MAX_THRESHOLD = 2 * DEFAULT_SPIKE_THRESHOLD
# default lists
DEFLIST_LATTICE2D_GEOMETRIES = ['triangular', 'squared', 'hexagonal']
DEFLIST_LATTICE2D_GEOABBRV = ['trLattice', 'sqLattice', 'hxLattice']
# extensions
ePDF = ".pdf"
eTXT = ".txt"
eBIN = ".bin"
eMP4 = ".mp4"
# paths
PATH_ROOTF = "LRG-Signed"
