# default values
DEFAULT_ENTROPY_STEPS = 1000
DEFAULT_ENTROPY_LEXPONENT = -3
DEFAULT_ENTROPY_HEXPONENT = 6
DEFAULT_SRC_DIR = "src/"
DEFAULT_PACKG_DIR = DEFAULT_SRC_DIR + "LRGSG_package/"
DEFAULT_PLOT_OUTDIR = "plot/"
DEFAULT_DATA_OUTDIR = "data/"
DEFAULT_GRAPH_OUTDIR = "graphs/"
DEFAULT_ISING_OUTDIR = "ising/"
DEFAULT_VOTER_OUTDIR = "voter/"
DEFAULT_LRGSG_OUTDIR = "lrgsg/"
DEFAULT_LATTICE2D_PATHABBRV = 'l2d_'
DEFAULT_LATTICE2D_GEOMETRY = 'squared'
DEFAULT_DATA_LATTICE2DSQ_OUTDIR = DEFAULT_DATA_OUTDIR + DEFAULT_LATTICE2D_PATHABBRV + DEFAULT_LATTICE2D_GEOMETRY
DEFAULT_ISING_NOCLUST = 5
DEFAULT_MAX_DIGITS_ROUND_SIGFIG = 18
DEFAULT_NUNMBER_AVERAGES = 100
DEFAULT_SPIKE_THRESHOLD = 0.05
DEFAULT_MAX_THRESHOLD = 2 * DEFAULT_SPIKE_THRESHOLD
# default lists
DEFLIST_LATTICE2D_GEOMETRIES = ['triangular', DEFAULT_LATTICE2D_GEOMETRY, 'hexagonal']
DEFLIST_LATTICE2D_GEOABBRV = ['trLattice', 'sqLattice', 'hxLattice']
# extensions
ePDF = ".pdf"
eTXT = ".txt"
eBIN = ".bin"
eMP4 = ".mp4"
# paths
PATH_ROOTF = "LRG-Signed"
