# default values
DEFAULT_ENTROPY_STEPS = 1000
DEFAULT_ENTROPY_LEXPONENT = -3
DEFAULT_ENTROPY_HEXPONENT = 6
DEFAULT_LATTICE2D_GEOMETRY = 'squared'
DEFAULT_MAX_DIGITS_ROUND_SIGFIG = 18
DEFAULT_NUNMBER_AVERAGES = 1000
DEFAULT_SPIKE_THRESHOLD = 0.05
DEFAULT_MAX_THRESHOLD = 2 * DEFAULT_SPIKE_THRESHOLD
# default lists
DEFLIST_LATTICE2D_GEOMETRIES = ['squared', 'triangular', 'hexagonal']
# extensions
ePDF = ".pdf"
eTXT = ".txt"
eBIN = ".bin"
# paths
PATH_ROOTF = 'LRG-Signed'
